// <auto-generated />
// ReSharper disable All

namespace flecs_hub
{
    public static unsafe partial class flecs
    {
        internal static ulong ecs_pair(ecs_entity_t pred, ecs_entity_t obj)
        {
            return pinvoke_ECS_PAIR() | ecs_entity_t_comb(obj.Data.Data, pred.Data.Data);
        }

        private static ulong ecs_entity_t_comb(ulong lo, ulong hi)
        {
            return (hi << 32) + lo;
        }
    }
}
