// <auto-generated />
// ReSharper disable All

using System.Runtime.CompilerServices;

namespace flecs_hub
{
    public static unsafe partial class flecs
    {
        // Roles
        public static ecs_id_t ECS_PAIR => pinvoke_ECS_PAIR();
        public static ecs_id_t ECS_OVERRIDE => pinvoke_ECS_OVERRIDE();
        
        // Relationships
        public static ecs_entity_t EcsIsA => pinvoke_EcsIsA();
        public static ecs_entity_t EcsDependsOn => pinvoke_EcsDependsOn();
        public static ecs_entity_t EcsChildOf => pinvoke_EcsChildOf();

        public static ecs_entity_t EcsSlotOf => pinvoke_EcsSlotOf();

        // Entity tags
        public static ecs_entity_t EcsPrefab => pinvoke_EcsPrefab();

        // System tags
        public static ecs_entity_t EcsPreFrame => pinvoke_EcsPreFrame();
        public static ecs_entity_t EcsOnLoad => pinvoke_EcsOnLoad();
        public static ecs_entity_t EcsPostLoad => pinvoke_EcsPostLoad();
        public static ecs_entity_t EcsPreUpdate => pinvoke_EcsPreUpdate();
        public static ecs_entity_t EcsOnUpdate => pinvoke_EcsOnUpdate();
        public static ecs_entity_t EcsOnValidate => pinvoke_EcsOnValidate();
        public static ecs_entity_t EcsPostUpdate => pinvoke_EcsPostUpdate();
        public static ecs_entity_t EcsPreStore => pinvoke_EcsPreStore();
        public static ecs_entity_t EcsOnStore => pinvoke_EcsOnStore();
        public static ecs_entity_t EcsPostFrame => pinvoke_EcsPostFrame();
        public static ecs_entity_t EcsPhase => pinvoke_EcsPhase();


        internal static ulong ecs_pair(ecs_entity_t pred, ecs_entity_t obj)
        {
            return ECS_PAIR.Data | ecs_entity_t_comb(obj.Data.Data, pred.Data.Data);
        }

        internal static ulong ecs_childof(ecs_entity_t e)
        {
            return ecs_pair(EcsChildOf, e);
        }

        internal static ulong ecs_entity_t_comb(ulong lo, ulong hi)
        {
            return (hi << 32) + (uint)lo;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static ecs_entity_t ecs_pair_first(ecs_world_t* world, ecs_entity_t entity)
        {
            var value = ECS_PAIR_FIRST(entity.Data.Data);
            return ecs_get_alive(world, *(ecs_entity_t*)&value);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static ecs_entity_t ecs_pair_second(ecs_world_t* world, ecs_entity_t entity)
        {
            var value = ECS_PAIR_SECOND(entity.Data.Data);
            return ecs_get_alive(world, *(ecs_entity_t*)&value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static ulong ECS_PAIR_FIRST(ulong entity)
        {
            var value = entity & ECS_COMPONENT_MASK;
            return ecs_entity_t_hi(value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static ulong ECS_PAIR_SECOND(ulong entity)
        {
            var value = entity;
            return ecs_entity_t_lo(value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static uint ecs_entity_t_hi(ulong value)
        {
            return (uint)(value >> 32);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static uint ecs_entity_t_lo(ulong value)
        {
            return (uint)value;
        }
    }
}
