name: "Bindgen"

on:
  workflow_call:

jobs:

  bindgen-ast-job:
    name: "Bindgen AST target-platform"
    runs-on: ${{ matrix.platform.os }}
    if: github.actor == 'dependabot[bot]' || github.actor == 'lithiumtoast' || github.actor == 'BlackPhoenix134'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows, os: windows-latest, rid: win, config_filename: config-windows.json }
          - { name: macOS, os: macos-latest, rid: osx, config_filename: config-macos.json }
          - { name: Linux, os: ubuntu-latest, rid: linux, config_filename: config-linux.json }

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: "Install .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: "Install CAstFfi"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.CAstFfi.Tool

      - name: "Read C code: Linux dependencies"
        if: runner.os == 'Linux'
        run: sudo apt-get install gcc-aarch64-linux-gnu

      - name: "Read C code: extract ${{ matrix.platform.rid }}"
        shell: bash
        run: cd ./bindgen && castffi extract --config "./${{ matrix.platform.config_filename }}"

      - name: "Upload C code platform abstract syntax trees"
        uses: actions/upload-artifact@v2
        with:
          name: "ast-${{ matrix.platform.rid }}"
          path: "./bindgen/ast"

  bindgen-cs-job:
    name: "Bindgen AST cross-platform"
    needs: [bindgen-ast-job]
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2
        with:
          submodules: 'false'

      - name: "Download C code platform abstrast syntax trees (win)"
        uses: actions/download-artifact@v1
        with:
          name: "ast-win"
          path: "./bindgen/ast"

      - name: "Download C code platform abstrast syntax trees (osx)"
        uses: actions/download-artifact@v1
        with:
          name: "ast-osx"
          path: "./bindgen/ast"

      - name: "Download C code platform abstrast syntax trees (linux)"
        uses: actions/download-artifact@v1
        with:
          name: "ast-linux"
          path: "./bindgen/ast"

      - name: "Install .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: "Install CAstFfi"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.CAstFfi.Tool

      - name: "Read C code: generate cross-platform AST"
        shell: bash
        run: cd ./bindgen && castffi merge --inputDirectoryPath "./ast" --outputFilePath "./ast-cross-platform.json"

      - name: "Upload cross-platform AST"
        uses: actions/upload-artifact@v2
        with:
          name: "bindgen-cs"
          path: "./bindgen/ast-cross-platform.json"

      # - name: "Upload generated C# code"
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: "bindgen-cs"
      #     path: "./src/cs/production/Flecs/flecs.cs"
