name: "Commit generated C# code"

on:
  workflow_call:

permissions: write-all

jobs:

  commit-job:
    name: "Commit generated C# code"
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'lithiumtoast' || github.actor == 'BlackPhoenix134'

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2 
        with:
          submodules: 'false'

      - name: "Download changes to commit"
        id: download
        uses: actions/download-artifact@v3
        with:
          name: "bindgen-cs"
          path: "./src/cs/production/Flecs"

      - name: "Echo download path"
        run: echo ${{steps.download.outputs.download-path}}

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'lithiumtoast'
          author_email: 'lithiumtoast@users.noreply.github.com'
          message: "Update C# bindings"
